### ISSUE TITLE
Write alembic migration for Package model to add ssh url of the git repository 

### ISSUE THREAD

**Issue by rahulrrixe** [fedora-infra/fresque#6]
Currently Package Model doesn't have column for the ssh url of the git repository.

**Comment by pypingou** [comment]
hm, not sure what you mean here, would the ssh url be that different?

**Comment by rahulrrixe** [comment]
@pypingou I am trying to add ssh url of the git repository to Package model. It will not be that much different we can follow a common pattern like <code> ssh git@fedorareveiwserver.org:/var/git/username</code> during repo creation, which I am doing.

**Comment by pypingou** [comment]
So why storing it in the database?

**Comment by rahulrrixe** [comment]
@pypingou you are right. we don't need it. Initially I thought we can use this to track whether the package have their linked git repo but it doesn't make sense as every package is going to have their git repo.

**Comment by pypingou** [comment]
I like the way you open ticket for everything you have in mind, it allows us to discuss and see how you approach things, good idea! :)

**Comment by rahulrrixe** [comment]
@pypingou thanks :0

**Comment by ralphbean** [comment]
Closing this since it seems to be resolved.
