### ISSUE TITLE
Discuss Fresque development with the Environments & Stacks WG

### ISSUE THREAD

**Issue by ncoghlan** [fedora-infra/fresque#9]
Over in the Environments & Stacks working group, we're starting to ask some serious questions about how we might potentially redesign Fedora's package review process to better meet the needs of application development teams in addition to operations teams: https://fedoraproject.org/wiki/Env_and_Stacks/Projects/PackageReviewProcessRedesign

While those are only preliminary discussions at this point (and any actual changes would go through the normal Fedora change control process), they do highlight that if E&S does head in this direction, we're going to need to commit to helping out with any associated changes to Fresque and fedora-review.

So this is just a preliminary heads up that the folks interested in Fresque may also be interested in the work we're doing in the Environments & Stacks working group :)

**Comment by pypingou** [comment]
Fresque has been discussed quickly when the E&S WG was created but since not much happened since (until the current GSoC), there wasn't much to discuss so far.

I am already on the E&S list and while @abompard is the official upstream for this project, I can probably contribute to the discussions the WG has.

**Comment by ncoghlan** [comment]
After an initial look at using Fresque directly, I ended up creating a Fresque fork to tackle the "initial upstream project review" phase of redistribution: https://github.com/ncoghlan/downstreaming

Background on what would be in scope for that review stage: https://fedoraproject.org/wiki/Env_and_Stacks/Projects/PackageReviewProcessRedesign#Aleph_4:_Redistributed_components

Some additional details on the major changes in the fork: https://github.com/ncoghlan/downstreaming/commit/f8c82cad2c8610b13695391066e4a94dbcae201b

The TODO file in the repo shows one of the major "trajectory" differences between Fresque and Downstreaming, which is that I'd like Downstreaming deployment to be independent of the details of Fedora's infrastructure, focusing on Kubernetes for deployment management, and the combination of Apache modules and Flask-User for authentication & authorization management.

**Comment by pypingou** [comment]
Is the idea to have the application run by the Fedora infrastructure? Because currently we do no have any docker/kubernetes deployed anywhere.

**Comment by ncoghlan** [comment]
It's still just a Flask app that runs under mod_wsgi - setting up good Docker/Kubernetes/OpenShift v3 deployment support is a priority for my own near term use case, but other deployment options will still work.

Replacing Fresque's strict dependency on FAS with Apache level authentication and a provider independent authorization management library is a different matter - I need the service to be deployable against any modern standards compliant identity management system.

**Comment by pypingou** [comment]
> I need the service to be deployable against any modern standards compliant identity management system.

And ipsilon isn't one?

**Comment by pypingou** [comment]
Oh, sorry I read your `any` as `a` which made me understand your sentence in a different way than what you meant.

**Comment by ncoghlan** [comment]
Yeah, Ipsilon qualifies as a standards compliant backend, it's specifically the FAS client libraries I'm planning to move away from (probably to https://pythonhosted.org/Flask-Security/ at the application level).

**Comment by pypingou** [comment]
If you use flask-openid you will remain compatible with FAS while being compatible w/ other openid provider if you like

**Comment by ncoghlan** [comment]
I'm after SAML and Kerberos compatibility as well, which means pushing authentication down to the web server tier, and only dealing with authorization at the application level.

**Comment by pypingou** [comment]
ok, cool :)
